"""Generate native vector paths for Android and iOS from the same body diagram.

The diagram is a schematic. Bilateral regions share a colour because exercise
percentages do not record left/right work separately. No downloaded artwork.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / "docs/muscle-map.json").read_text(encoding="utf-8"))
COUNTS = {"M": 2, "L": 2, "Q": 4, "C": 6, "Z": 0}


def commands(text):
    tokens = re.findall(r"[MLQCZ]|-?\d+(?:\.\d+)?", text)
    result = []
    i = 0
    while i < len(tokens):
        kind = tokens[i]
        count = COUNTS[kind]
        result.append((kind, [float(x) for x in tokens[i + 1:i + 1 + count]]))
        i += count + 1
    return result


def mirrored(items):
    return [(kind, [data["width"] - x if i % 2 == 0 else x for i, x in enumerate(values)])
            for kind, values in items]


def outline():
    half = commands(data["outlineHalf"])
    previous = half[0][1]
    reverse = []
    for kind, values in half[1:]:
        if kind == "C":
            reverse.append((kind, values[2:4] + values[:2] + previous))
        elif kind == "Q":
            reverse.append((kind, values[:2] + previous))
        else:
            reverse.append((kind, previous))
        previous = values[-2:]
    return half + mirrored(list(reversed(reverse))) + [("Z", [])]


def region_commands(region):
    items = commands(region["path"])
    return items + mirrored(items) if region.get("mirror") else items


def number(value):
    return format(value, "g")


def kotlin_path(items, indent):
    names = {"M": "moveTo", "L": "lineTo", "Q": "quadraticTo", "C": "cubicTo", "Z": "close"}
    return "Path().apply {\n" + "\n".join(
        indent + "    " + names[kind] + "(" + ", ".join(number(v) + "f" for v in values) + ")"
        for kind, values in items) + "\n" + indent + "}"


def swift_path(items, indent):
    def point(values):
        return "CGPoint(x: " + number(values[0]) + ", y: " + number(values[1]) + ")"
    lines = []
    for kind, values in items:
        if kind == "Z":
            call = "path.closeSubpath()"
        elif kind in ("M", "L"):
            call = "path." + ("move" if kind == "M" else "addLine") + "(to: " + point(values) + ")"
        elif kind == "Q":
            call = "path.addQuadCurve(to: " + point(values[2:]) + ", control: " + point(values[:2]) + ")"
        else:
            call = "path.addCurve(to: " + point(values[4:]) + ", control1: " + point(values[:2]) + ", control2: " + point(values[2:4]) + ")"
        lines.append(indent + "    " + call)
    return "Path { path in\n" + "\n".join(lines) + "\n" + indent + "}"


def strings(items):
    return ", ".join(json.dumps(item, ensure_ascii=False) for item in items)


header = "// Generated by tools/generate_muscle_map.py; edit docs/muscle-map.json.\n"
kotlin = header + "package com.codex.gymtracker\n\nimport androidx.compose.ui.graphics.Path\n\n"
kotlin += "internal data class MuscleMapRegion(val id: String, val label: String, val muscleKeys: List<String>, val path: Path)\n\n"
kotlin += "internal object MuscleMapGeometry {\n    const val width = " + number(data["width"]) + "f\n    const val height = " + number(data["height"]) + "f\n"
kotlin += "    val outline = " + kotlin_path(outline(), "    ") + "\n"
swift = header + "import SwiftUI\n\nstruct MuscleMapRegion {\n    let id: String\n    let label: String\n    let muscleKeys: [String]\n    let path: Path\n}\n\n"
swift += "enum MuscleMapGeometry {\n    static let width: CGFloat = " + number(data["width"]) + "\n    static let height: CGFloat = " + number(data["height"]) + "\n"
swift += "    static let frontOutline = " + swift_path(outline(), "    ") + "\n    static let backOutline = frontOutline\n"
for side in ("front", "back"):
    kotlin += "    val " + side + " = listOf(\n"
    swift += "    static let " + side + ": [MuscleMapRegion] = [\n"
    for region in data[side]:
        props = strings([region["id"], region["label"]])
        kotlin += "        MuscleMapRegion(" + props + ", listOf(" + strings(region["muscleKeys"]) + "), " + kotlin_path(region_commands(region), "        ") + "),\n"
        swift += "        MuscleMapRegion(id: " + json.dumps(region["id"]) + ", label: " + json.dumps(region["label"], ensure_ascii=False) + ", muscleKeys: [" + strings(region["muscleKeys"]) + "], path: " + swift_path(region_commands(region), "        ") + "),\n"
    kotlin += "    )\n"
    swift += "    ]\n"
kotlin += "}\n"
swift += "}\n"
kotlin_file = ROOT / "app/src/main/java/com/codex/gymtracker/MuscleMapGeometry.kt"
swift_file = ROOT / "ios/GymTracker/MuscleMapGeometry.swift"
kotlin_file.parent.mkdir(parents=True, exist_ok=True)
swift_file.parent.mkdir(parents=True, exist_ok=True)
kotlin_file.write_text(kotlin, encoding="utf-8")
swift_file.write_text(swift, encoding="utf-8")
print("Generated shared front/back paths for Android and iOS.")
